"""add suspended column

Revision ID: 486202efaaad
Revises: 44539b6c1b5e
Create Date: 2026-06-17 22:37:55.323847

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = '486202efaaad'
down_revision = '44539b6c1b5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('suspended',
               existing_type=mssql.BIT(),
               nullable=True,
               existing_server_default=sa.text('((0))'))
        batch_op.alter_column('feed_entries',
               existing_type=mssql.BIT(),
               nullable=True,
               existing_server_default=sa.text('((0))'))
        batch_op.alter_column('amend_entry',
               existing_type=mssql.BIT(),
               nullable=True,
               existing_server_default=sa.text('((0))'))
        batch_op.alter_column('provision1',
               existing_type=mssql.BIT(),
               nullable=True,
               existing_server_default=sa.text('((0))'))
        batch_op.alter_column('provision2',
               existing_type=mssql.BIT(),
               nullable=True,
               existing_server_default=sa.text('((0))'))
        batch_op.alter_column('provision3',
               existing_type=mssql.BIT(),
               nullable=True,
               existing_server_default=sa.text('((0))'))
        batch_op.alter_column('provision4',
               existing_type=mssql.BIT(),
               nullable=True,
               existing_server_default=sa.text('((0))'))
        batch_op.alter_column('provision5',
               existing_type=mssql.BIT(),
               nullable=True,
               existing_server_default=sa.text('((0))'))
        batch_op.alter_column('provision6',
               existing_type=mssql.BIT(),
               nullable=True,
               existing_server_default=sa.text('((0))'))
        batch_op.alter_column('provision7',
               existing_type=mssql.BIT(),
               nullable=True,
               existing_server_default=sa.text('((0))'))
        batch_op.alter_column('provision8',
               existing_type=mssql.BIT(),
               nullable=True,
               existing_server_default=sa.text('((0))'))
        batch_op.alter_column('provision9',
               existing_type=mssql.BIT(),
               nullable=True,
               existing_server_default=sa.text('((0))'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('provision9',
               existing_type=mssql.BIT(),
               nullable=False,
               existing_server_default=sa.text('((0))'))
        batch_op.alter_column('provision8',
               existing_type=mssql.BIT(),
               nullable=False,
               existing_server_default=sa.text('((0))'))
        batch_op.alter_column('provision7',
               existing_type=mssql.BIT(),
               nullable=False,
               existing_server_default=sa.text('((0))'))
        batch_op.alter_column('provision6',
               existing_type=mssql.BIT(),
               nullable=False,
               existing_server_default=sa.text('((0))'))
        batch_op.alter_column('provision5',
               existing_type=mssql.BIT(),
               nullable=False,
               existing_server_default=sa.text('((0))'))
        batch_op.alter_column('provision4',
               existing_type=mssql.BIT(),
               nullable=False,
               existing_server_default=sa.text('((0))'))
        batch_op.alter_column('provision3',
               existing_type=mssql.BIT(),
               nullable=False,
               existing_server_default=sa.text('((0))'))
        batch_op.alter_column('provision2',
               existing_type=mssql.BIT(),
               nullable=False,
               existing_server_default=sa.text('((0))'))
        batch_op.alter_column('provision1',
               existing_type=mssql.BIT(),
               nullable=False,
               existing_server_default=sa.text('((0))'))
        batch_op.alter_column('amend_entry',
               existing_type=mssql.BIT(),
               nullable=False,
               existing_server_default=sa.text('((0))'))
        batch_op.alter_column('feed_entries',
               existing_type=mssql.BIT(),
               nullable=False,
               existing_server_default=sa.text('((0))'))
        batch_op.alter_column('suspended',
               existing_type=mssql.BIT(),
               nullable=False,
               existing_server_default=sa.text('((0))'))

    # ### end Alembic commands ###
